name: Master Workflow - Build and deploy to production
on:
  pull_request:
    branches: [ main ]
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [ "event-triggered-by-jira" ]
    
jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps:       
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: DEVOPS-1
        comment: ${{ github.event.pusher.name }} pushed to repository- ${{ github.event.repository.full_name }}    
